### Get users
GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNzE0MzA1NjcwLCJleHAiOjE3MTQzNDE2NzB9.8vGxTbgdXmybkEet2g1H54LQe0FTlP6cLUMBgQjKmvI


### Create User
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "test123"
}

### Login User
POST http://localhost:3000/login
content-type: application/json

{
    "username": "admin",
    "password": "test123"
}